# Generated by Django 4.0.1 on 2022-01-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictsInRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='maps.node')),
                ('id_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer', to='maps.node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conflictsinrange',
            constraint=models.UniqueConstraint(fields=('id_influencer', 'id_conflict'), name='conflict_in_range_influencer'),
        ),
    ]
