# Generated by Django 4.0.1 on 2022-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_conflictsinrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictsinrange',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
