# Generated by Django 4.0.1 on 2022-03-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_city_nb_click'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-nb_click']},
        ),
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.IntegerField(unique=True),
        ),
    ]
